# -*- coding: utf-8 -*-
"""model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IhuvRLHYLhgQL_RXtVPxgJEYn2HueQ7o
"""

# Commented out IPython magic to ensure Python compatibility.
import torch
import torchvision
import torch.nn.functional as F
import matplotlib.pyplot as plt
import torch.nn as nn
import torch.optim as optim
from torchvision import transforms, datasets

import numpy as np
import pickle
from sklearn.model_selection import train_test_split
import random
from sklearn import preprocessing
# %matplotlib inline


class MNIST_Dataset(torch.utils.data.Dataset):
  def __init__(self, X, y, transform = False):
        'Initialization'
        #X for images, y for labels
        self.X = X
        self.y = y
        self.transform = transform

  def __len__(self):
        'Denotes the total number of samples'
        return len(self.X)

  def __getitem__(self, index):
        'Generates one sample of data'
        # Select sample
        image = self.X[index]
        label = self.y[index]
        #X = self.transform(image)
        return image, label